[package]
name = "runner_gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkano = "0.35.2"
vulkano-shaders = "0.35.0"
eager2 = "1.1.4"
smallvec = "1.15.1"

[build-dependencies]
spirv-builder = {git = "https://github.com/rust-gpu/rust-gpu"}
